package view;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author daviw
 */
public class FrmSorteio extends javax.swing.JFrame {

    /**
     * Creates new form FrmSorteio
     */
    public FrmSorteio() {
        initComponents();
    }

    // Lista de números a serem sorteados simulando o globo de sorteio
    ArrayList<Integer> listaNumeros = new ArrayList();
// Gerador de numeros aleatórios
    Random geradorNumero;
// Para Saber quantos números ainda faltam para ser sorteado
    int quantidadeFaltante = 0;
//ordenação do sorteio, meramente para exibir qual a posição foi sorteado, primeiro, segundo, etc...
    int ordem = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JLNumeroSorteado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTFQuantidadeNumerosSorteados = new javax.swing.JTextField();
        JBNovo = new javax.swing.JButton();
        JBSortear = new javax.swing.JButton();
        JBLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTANumerosSorteados = new javax.swing.JTextArea();
        JBFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sorteio");

        jLabel1.setText("Sorteio");

        jLabel2.setText("Quantidade de números sorteados:");

        JLNumeroSorteado.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        JLNumeroSorteado.setText("0");

        jLabel4.setText("Número Sorteado");

        JTFQuantidadeNumerosSorteados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFQuantidadeNumerosSorteadosActionPerformed(evt);
            }
        });

        JBNovo.setText("Novo");
        JBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNovoActionPerformed(evt);
            }
        });

        JBSortear.setText("Sortear");
        JBSortear.setEnabled(false);
        JBSortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSortearActionPerformed(evt);
            }
        });

        JBLimpar.setText("Limpar");
        JBLimpar.setEnabled(false);
        JBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLimparActionPerformed(evt);
            }
        });

        JTANumerosSorteados.setColumns(20);
        JTANumerosSorteados.setRows(5);
        jScrollPane1.setViewportView(JTANumerosSorteados);

        JBFechar.setText("Fechar");
        JBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(JLNumeroSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(JBFechar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JTFQuantidadeNumerosSorteados, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(JBNovo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JBSortear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JBLimpar)))))
                        .addGap(0, 38, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JTFQuantidadeNumerosSorteados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JLNumeroSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBNovo)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBSortear)
                            .addComponent(JBLimpar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBFechar)
                        .addContainerGap(36, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBSortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSortearActionPerformed
        if (!listaNumeros.isEmpty()) { //Se existe números a serem sorteados então
// Cria um novo gerador de número aleatório (Random)
            geradorNumero = new Random();
// Pega um número aleatório entre 0 e o valor de quantidadeFaltante
            int indice = geradorNumero.nextInt(quantidadeFaltante);
// Depois do sorteio retira a quantidade restante em -1
            quantidadeFaltante--;
// Indica qual a posição que foi sorteado, primeiro, segundo, etc.
            ordem++;
// Adiciona o numero sorteado no JTextArea
            JTANumerosSorteados.append(ordem + "º sorteado: " + listaNumeros.get(indice).toString() + "\n");
// Mostra o número sorteado por meio do Label
            JLNumeroSorteado.setText(listaNumeros.get(indice).toString());
            listaNumeros.remove(indice); // Remove o número da lista
        } else { // Se acabou os numeros a serem sorteados
            JOptionPane.showMessageDialog(null, "Não Há números a serem sorteados \n inicie um novo Sorteio");
            this.JBNovo.setEnabled(true); // Habilita o botão novo
            this.JBSortear.setEnabled(false); // Desabilita o botão sortear
            this.JBLimpar.setEnabled(false); // Desabilita o botão cancelar
        }
    }//GEN-LAST:event_JBSortearActionPerformed

    private void JTFQuantidadeNumerosSorteadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFQuantidadeNumerosSorteadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFQuantidadeNumerosSorteadosActionPerformed

    private void JBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBFecharActionPerformed
        // Encerra o programa
        System.exit(0);
    }//GEN-LAST:event_JBFecharActionPerformed

    private void JBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLimparActionPerformed
        // Habilita o botão novo
        this.JBNovo.setEnabled(true);
        // Desabilita o botão sortear
        this.JBSortear.setEnabled(false);
        // Desabilita o botão cancelar
        this.JBLimpar.setEnabled(false);

    }//GEN-LAST:event_JBLimparActionPerformed

    private void JBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNovoActionPerformed
        // Recupera a quantidade de números a serem sorteados
        int quantidadeNumeroSorteados = Integer.parseInt(this.JTFQuantidadeNumerosSorteados.getText());

        JTANumerosSorteados.setText(""); // Limpa o text area
        listaNumeros.clear(); // Esvazia a lista
        JLNumeroSorteado.setText("0"); // Zera o label do número sorteado
        // Para saber quantos números ainda faltam para ser sorteado
        quantidadeFaltante = 0;
        ordem = 0;

        if (quantidadeNumeroSorteados > 0) { // Verifica se a quantidade é maior que 0
        // Adiciona os números de 1 até quantidade sorteados na lista
            for (int i = 1; i <= quantidadeNumeroSorteados; i++) {
                listaNumeros.add(i);
            }
            quantidadeFaltante = quantidadeNumeroSorteados;
            this.JBNovo.setEnabled(false); // Desabilita o botão novo
            this.JBSortear.setEnabled(true); // Habilita o botão sortear
            this.JBLimpar.setEnabled(true); // Habilita o botão cancelar
        } else {
            JOptionPane.showMessageDialog(null, "Valor deve ser maior que 0!");
        }
    }//GEN-LAST:event_JBNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSorteio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSorteio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSorteio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSorteio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSorteio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBFechar;
    private javax.swing.JButton JBLimpar;
    private javax.swing.JButton JBNovo;
    private javax.swing.JButton JBSortear;
    private javax.swing.JLabel JLNumeroSorteado;
    private javax.swing.JTextArea JTANumerosSorteados;
    private javax.swing.JTextField JTFQuantidadeNumerosSorteados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
